### ISSUE TITLE
Yellow text messages

### ISSUE THREAD

**Issue by martinjh99** [DlljsCodes/exploration-progress#18]
Yellow text does not go well with background colour.   See link.
![image](https://user-images.githubusercontent.com/8138314/129741718-d4e3d053-9737-4ee1-bc4c-143204c31fff.png)

Can you change it to Black?

**Comment by martinjh99** [comment]
It works if you change EDMC's theme to dark but still needs fixing with the default setting.

**Comment by DlljsCodes** [comment]
Hello! I'm sorry for the inconvenience. However I still would like to emphasise the text with a different colour than the rest of the interface. I changed it to orange; does this look any better to you? If it does, I can get a new update out very shortly.
![image](https://user-images.githubusercontent.com/64469452/130329106-add0360c-9a18-449c-b2ad-0048319c787c.png)

**Comment by martinjh99** [comment]
Looks good to me in the screenshot :) Works for me,

**Comment by DlljsCodes** [comment]
Update to [version 1.0.4](https://github.com/DlljsCodes/exploration-progress/releases/tag/v1.0.4).
