### ISSUE TITLE
Broken on EDMC v5.11.0 and higher

### ISSUE THREAD

**Issue by Kepas-Beleglorn** [DlljsCodes/exploration-progress#22]
Plugin does not load since EDMC v5.11.0, marked by EDMC as "broken".

**Comment by DlljsCodes** [comment]
I'm unable to replicate the issue with EDMC version 5.11.1 and plugin version 1.0.5. 

If you are still encountering this issue, please run EDMC, making sure that exploration-progress is enabled, and replicate the issue (up until the notice about the plugin being broken appears). Then, locate the latest EDMC [debug log file](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files) and [plain log file](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#plain-log-file), and attach both to a new comment here.

**Comment by Kepas-Beleglorn** [comment]
Here are the requested log files. I hope you can find the cause of the problem. Let me know, if I can be of further assistance.
[EDMarketConnector.log](https://github.com/user-attachments/files/15827633/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/15827637/EDMarketConnector-debug.log)

**Comment by Kepas-Beleglorn** [comment]
I just had a brief look at the debug file. One line catches the eye:
`ImportError: cannot import name 'get_coords_from_edsm' from 'edsm' (C:\Users\peter\AppData\Local\EDMarketConnector\plugins\edsm.py)

I put my EDMC plugins into a custom path: `e:\Games\Tools\EliteDangerous\EDMC\plugins\` and created a symbolic link using `mklink` on `%LOCALAPPDATA%\EDMarketConnector\plugins` pointing to that directory.

Maybe this causes the issue?

I also use the Autopath plugin, which works just fine.

**Comment by DlljsCodes** [comment]
The plugin is trying to find a function called `get_coords_from_edsm` inside the file `edsm.py`, but can't find it. However, it's trying to find it **from the main plugin directory, not the Exploration Progress directory inside it**.

Can you confirm that these files are present in the directory `exploration-progress-1.0.5` inside the `plugins` directory, either in the default path or the custom path?
- [ ] `calculate.py`
- [ ] `edsm.py`
- [ ] `load,py`
- [ ] `system.py`

**Comment by Kepas-Beleglorn** [comment]
Left is the `mlink`-ed folder, right is the actual path. So yes, all the files you mentioned are present within the  directory `exploration-progress-1.0.5` inside the `plugins` directory
![image](https://github.com/DlljsCodes/exploration-progress/assets/77459606/c3a6fd80-3e0a-40a5-809b-98fb1c739745)
![image](https://github.com/DlljsCodes/exploration-progress/assets/77459606/8d6d5f38-1004-4053-8b1d-165c523d515c)
![image](https://github.com/DlljsCodes/exploration-progress/assets/77459606/7fb4260c-1524-4186-bda8-9779f7d9583c)

**Comment by DlljsCodes** [comment]
Try downloading [this `edsm.py` file](https://github.com/DlljsCodes/exploration-progress/blob/febe295ce22484f94fa014b2d4a11ab0b847acfe/edsm_api.py) and [this `system.py` file](https://github.com/DlljsCodes/exploration-progress/blob/febe295ce22484f94fa014b2d4a11ab0b847acfe/system.py) (click on the "Download raw file" button in the top right of the code display) and putting them into the Exploration Progress plugin directory, replacing the existing `system.py` file with the new one. Delete the old `edsm.py` file **from the Exploration Progress plugin directory, not the main plugin directory**, then run EDMC and see if that fixes it.

**Comment by Kepas-Beleglorn** [comment]
That works perfectly. Thanks for the quick fix.!

**Comment by DlljsCodes** [comment]
Update to [version 1.0.6](https://github.com/DlljsCodes/exploration-progress/releases/tag/v1.0.6) (if you want a "formal" fix).
